name: Build

inputs:
  DOCKER_REGISTRY_URL:
    type: string
    required: true
  DOCKER_REGISTRY_USERNAME:
    type: string
    required: true
  DOCKER_REGISTRY_PASSWORD:
    type: string
    required: true

runs:
  using: 'composite'
  steps:
    - name: Login to private registry
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.DOCKER_REGISTRY_URL }}
        username: ${{ inputs.DOCKER_REGISTRY_USERNAME }}
        password: ${{ inputs.DOCKER_REGISTRY_PASSWORD }}
