name: Build

inputs:
  DOKPLOY_URL:
    type: string
    required: true
  DEPLOY_APP_ID:
    type: string
    required: true

runs:
  using: 'composite'
  steps:
    - name: Trigger Dokploy deployment
      id: trigger
      shell: bash
      run: |
        URL="${{ inputs.DOKPLOY_URL }}/api/deploy/${{ inputs.DEPLOY_APP_ID }}"
        status=$(curl --silent --output /dev/null --write-out "%{http_code}" "$URL")
        echo "response=$status" >> $GITHUB_OUTPUT

    - name: Check deployment trigger
      if: steps.trigger.outputs.response != '200'
      shell: bash
      run: |
        echo "::error::Deployment webhook fall with HTTP ${{ steps.trigger.outputs.response }}"
        exit 1
