export enum Region {
  CRIMEA = 1,
  VINNYTSKA = 2,
  VOLYNSKA = 3,
  DNIPROPETROVSKA = 4,
  DONETSKA = 5,
  ZHYTOMYRSKA = 6,
  ZAKARPATSKA = 7,
  ZAPORIZKA = 8,
  IVANO_FRANKIVSKA = 9,
  KYIVSKA = 10,
  KIROVOHRADSKA = 11,
  LUHANSKA = 12,
  LVIVSKA = 13,
  MYKOLAIVSKA = 14,
  ODESKA = 15,
  POLTAVSKA = 16,
  RIVNENSKA = 17,
  SUMSKA = 18,
  TERNOPILSKA = 19,
  KHARKIVSKA = 20,
  KHERSONSKA = 21,
  KHMELNYTSKA = 22,
  CHERKASKA = 23,
  CHERNIVETSKA = 24,
  CHERNIHIVSKA = 25,
}

export const REGION_TITLE: Record<Region, string> = {
  [Region.CRIMEA]: 'Автономна Республіка Крим',
  [Region.VINNYTSKA]: 'Вінницька',
  [Region.VOLYNSKA]: 'Волинська',
  [Region.DNIPROPETROVSKA]: 'Дніпропетровська',
  [Region.DONETSKA]: 'Донецька',
  [Region.ZHYTOMYRSKA]: 'Житомирська',
  [Region.ZAKARPATSKA]: 'Закарпатська',
  [Region.ZAPORIZKA]: 'Запорізька',
  [Region.IVANO_FRANKIVSKA]: 'Івано-Франківська',
  [Region.KYIVSKA]: 'Київська',
  [Region.KIROVOHRADSKA]: 'Кіровоградська',
  [Region.LUHANSKA]: 'Луганська',
  [Region.LVIVSKA]: 'Львівська',
  [Region.MYKOLAIVSKA]: 'Миколаївська',
  [Region.ODESKA]: 'Одеська',
  [Region.POLTAVSKA]: 'Полтавська',
  [Region.RIVNENSKA]: 'Рівненська',
  [Region.SUMSKA]: 'Сумська',
  [Region.TERNOPILSKA]: 'Тернопільська',
  [Region.KHARKIVSKA]: 'Харківська',
  [Region.KHERSONSKA]: 'Херсонська',
  [Region.KHMELNYTSKA]: 'Хмельницька',
  [Region.CHERKASKA]: 'Черкаська',
  [Region.CHERNIVETSKA]: 'Чернівецька',
  [Region.CHERNIHIVSKA]: 'Чернігівська',
};

export const REGION_INFO: Record<Region, { north: number; south: number; west: number; east: number }> = {
  [Region.CRIMEA]: { north: 45.3, south: 44.3, west: 32.0, east: 36.6 },
  [Region.VINNYTSKA]: { north: 49.55, south: 48.1, west: 27.3, east: 29.7 },
  [Region.VOLYNSKA]: { north: 51.25, south: 50.0, west: 23.5, east: 26.0 },
  [Region.DNIPROPETROVSKA]: { north: 49.0, south: 47.0, west: 33.0, east: 36.2 },
  [Region.DONETSKA]: { north: 49.9, south: 47.7, west: 37.2, east: 39.8 },
  [Region.ZHYTOMYRSKA]: { north: 51.6, south: 49.8, west: 27.2, east: 29.6 },
  [Region.ZAKARPATSKA]: { north: 49.3, south: 47.5, west: 22.1, east: 24.4 },
  [Region.ZAPORIZKA]: { north: 48.8, south: 46.9, west: 35.0, east: 37.8 },
  [Region.IVANO_FRANKIVSKA]: { north: 49.2, south: 47.3, west: 23.8, east: 25.8 },
  [Region.KYIVSKA]: { north: 51.7, south: 49.9, west: 29.9, east: 32.2 },
  [Region.KIROVOHRADSKA]: { north: 50.5, south: 48.8, west: 31.0, east: 33.1 },
  [Region.LUHANSKA]: { north: 49.5, south: 47.3, west: 38.0, east: 40.5 },
  [Region.LVIVSKA]: { north: 50.7, south: 49.0, west: 23.5, east: 25.8 },
  [Region.MYKOLAIVSKA]: { north: 48.3, south: 46.4, west: 30.8, east: 33.0 },
  [Region.ODESKA]: { north: 48.2, south: 45.2, west: 29.3, east: 31.9 },
  [Region.POLTAVSKA]: { north: 50.5, south: 49.0, west: 32.2, east: 35.0 },
  [Region.RIVNENSKA]: { north: 51.4, south: 50.1, west: 25.5, east: 27.8 },
  [Region.SUMSKA]: { north: 52.2, south: 50.5, west: 33.5, east: 35.8 },
  [Region.TERNOPILSKA]: { north: 49.8, south: 48.2, west: 24.8, east: 26.5 },
  [Region.KHARKIVSKA]: { north: 50.5, south: 48.3, west: 35.0, east: 37.7 },
  [Region.KHERSONSKA]: { north: 47.8, south: 45.8, west: 32.8, east: 35.5 },
  [Region.KHMELNYTSKA]: { north: 50.6, south: 48.8, west: 26.1, east: 27.9 },
  [Region.CHERKASKA]: { north: 50.1, south: 48.3, west: 31.4, east: 33.5 },
  [Region.CHERNIVETSKA]: { north: 48.5, south: 47.9, west: 25.0, east: 26.6 },
  [Region.CHERNIHIVSKA]: { north: 52.1, south: 51.0, west: 31.3, east: 33.6 },
};
