export enum Region {
  CRIMEA = 1,
  VINNYTSKA = 2,
  VOLYNSKA = 3,
  DNIPROPETROVSKA = 4,
  DONETSKA = 5,
  ZHYTOMYRSKA = 6,
  ZAKARPATSKA = 7,
  ZAPORIZKA = 8,
  IVANO_FRANKIVSKA = 9,
  KYIVSKA = 10,
  KIROVOHRADSKA = 11,
  LUHANSKA = 12,
  LVIVSKA = 13,
  MYKOLAIVSKA = 14,
  ODESKA = 15,
  POLTAVSKA = 16,
  RIVNENSKA = 17,
  SUMSKA = 18,
  TERNOPILSKA = 19,
  KHARKIVSKA = 20,
  KHERSONSKA = 21,
  KHMELNYTSKA = 22,
  CHERKASKA = 23,
  CHERNIVETSKA = 24,
  CHERNIHIVSKA = 25,
}

export const REGION_TITLE: Record<Region, string> = {
  [Region.CRIMEA]: 'Автономна Республіка Крим',
  [Region.VINNYTSKA]: 'Вінницька',
  [Region.VOLYNSKA]: 'Волинська',
  [Region.DNIPROPETROVSKA]: 'Дніпропетровська',
  [Region.DONETSKA]: 'Донецька',
  [Region.ZHYTOMYRSKA]: 'Житомирська',
  [Region.ZAKARPATSKA]: 'Закарпатська',
  [Region.ZAPORIZKA]: 'Запорізька',
  [Region.IVANO_FRANKIVSKA]: 'Івано-Франківська',
  [Region.KYIVSKA]: 'Київська',
  [Region.KIROVOHRADSKA]: 'Кіровоградська',
  [Region.LUHANSKA]: 'Луганська',
  [Region.LVIVSKA]: 'Львівська',
  [Region.MYKOLAIVSKA]: 'Миколаївська',
  [Region.ODESKA]: 'Одеська',
  [Region.POLTAVSKA]: 'Полтавська',
  [Region.RIVNENSKA]: 'Рівненська',
  [Region.SUMSKA]: 'Сумська',
  [Region.TERNOPILSKA]: 'Тернопільська',
  [Region.KHARKIVSKA]: 'Харківська',
  [Region.KHERSONSKA]: 'Херсонська',
  [Region.KHMELNYTSKA]: 'Хмельницька',
  [Region.CHERKASKA]: 'Черкаська',
  [Region.CHERNIVETSKA]: 'Чернівецька',
  [Region.CHERNIHIVSKA]: 'Чернігівська',
};
