name: 🆕🔀 Pull Request [develop]
 
on:
  workflow_dispatch:
  pull_request:
    branches: ["develop"]

env:
  NAMESPACE: drmp
  PROJECT_NAME: frontend

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint
        uses: ./.github/actions/lint
